name: PostgreSQL service example
on: 
  push:
  workflow_dispatch:

jobs:
  postgres-container-job:
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run: node postgres-demo.js
        env:
          PGHOST: postgres
          PGPORT: 5432
          PGPASSWORD: postgres
          PGDATABASE: postgres
